config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show; end

  def new
   @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to @flat
    else
      render :new
    end
  end

  def update
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :number_of_guests %>
    <%= f.input :price_per_night %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary text-white" %>
    <%= link_to "Cancel", flats_path, class: "btn btn-danger text-white"%>
  </div>
<% end %>

app/views/flats/index.html.erb
<h1> All our flats </h1>
<p>All <%= @flats.count %> flats.</p>

<div class="d-flex flex-wrap justify-content-between">
  <% @flats.each do |flat| %>
    <div class="card" style="width: 18rem;">
      <%= image_tag("https://source.unsplash.com/random?sig=#{rand(0..999)}", size: "300x200", class: "card-img-top") %>
      <div class="card-body">
        <h5 class="card-title"> <%= flat.name %></h5>
        <p class="card-text"> <%= flat.address %></p>
        <div class="mb-3">
          <i class="fas fa-user-friends"> <%= flat.number_of_guests %></i>
          <i class="fas fa-euro-sign"> <%= flat.price_per_night %></i>
        </div>
        <div class="d-flex flex-wrap justify-content-between">
          <%= link_to "More info", flat_path(flat), class: "btn btn-primary text-white" %>
          <%= link_to "Edit", flat_path(flat), class: "btn btn-warning text-white" %>
          <%= link_to "Remove", flat_path(flat), class: "btn btn-danger text-white" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="row justify-content-center ">
    <div class="col-6 bg-light p-4">
      <h1>Add a new flat</h1>
      <%= render 'form', flat: @flat %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<h1> <%= @flat.name %> </h1>
<h3> <%= @flat.address %> </h3>

<h4>A bit more about this flat...</h4>
<p> <%= @flat.description %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsSimpleAirbnb</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-light bg-light px-3 mb-4">
    <a class="navbar-brand">Simple Airbnb</a>
    <form class="form-inline d-flex">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0 mx-2" type="submit">Search</button>
      <%= link_to "Add flat", new_flat_path, class: "btn btn-outline-primary my-2 my-sm-0 w-50" %>
      <!-- <button class="btn btn-outline-primary my-2 my-sm-0 w-50" type="submit">Add flat</button> -->
    </form>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>